# Generated by Django 2.1.2 on 2018-10-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('customer_address', models.CharField(db_index=True, max_length=64)),
                ('merchant_address', models.CharField(db_index=True, max_length=64)),
                ('deposit', models.PositiveIntegerField(default=0)),
                ('timeout', models.DateTimeField(blank=True, null=True)),
                ('refunded', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
