# Generated by Django 2.1.2 on 2018-10-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
