# Generated by Django 2.1.2 on 2018-10-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181022_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='transport_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
